### ISSUE TITLE
ConstraintValidator fires twice. Why?

### ISSUE THREAD

**Issue by beredim** [sdaschner/javaone-lightweight-ee#1]
Hi Sebastian,
I watched the respective video on youtube and browsed here to take a look at the source code.

I am noticing that the CloudNotTakenValidator isValid() method gets called twice when trying to POST a new resource. I cannot understand why this is happening and how to fix it.

1. Why does this happen?
2. Is this the expected behavior?
3. Any pointers as to how to fix this to run only once per request?

(Running on wildfly 10.1.0Final)

**Comment by sdaschner** [comment]
Hi beredim,

This is related to WildFly. I suppose Jackson implicitly calls Bean Validation when mapping the objects from JSON. The output should be the same -- validators should be stateless. TomEE, for example, only runs the validator once.
